internal-products:
  name: Internal Products
  project: 6 # ID of the project where issues for team repos are pushed
  permission: pull # Repo permission assigned to the team's members
  secrets: # Organization secrets used by team workflows.
    workflow-manage: IP_WORKFLOW_MANAGE_PAT
    issue-manage: IP_ISSUE_MANAGE_PAT
    repo-write: IP_REPO_WRITE_PAT
  members: # All members of the team
    - thomasplevy
    - eri-trabiccolo
    - vphat28
    - KristaButler
  owner: eri-trabiccolo # Default code owner for all team repos
  repos: # List of all repos owned by the team
    - caseproof-feature-tracker
    - coding-standards-js
    - coding-standards-php
    - cspf-auto-coupons
    - cspf-teams-manager
    - ground-level-php
    - ground-level-php-tests
    - ground-level-sample-plugin
    - growth-tools
    - heroic-knowledge-base-helpscout
    - hs-to-hkb-migrator
    - membermouse-com-2020
    - mothership-wp
    - my.wishlistmember.com
    - pkgs.cspf.co
    - org-admin
    - reseller_portal
    - sale-landing-pages
    - wishlistmember.com
  teams: # List of subteams, their members, and their permissions
    admins:
      name: Internal Products Admins
      permission: maintain
      members:
        - thomasplevy
        - eri-trabiccolo
    cust-success:
      name: Internal Products Customer Success
      permission: triage
      members:
        - support-person-1
    engineering:
      name: Internal Products Engineering
      permission: maintain
      members:
        - thomasplevy
        - eri-trabiccolo
        - vphat28

