name: 'Organization Project Automation Workflow'
description: 'Action to copy the project automation workflow across company's repositories'
inputs:
  secrets:
    description: 'GitHub secrets'
  org:
    description: 'The GitHub organization slug'
runs:
  using: 'node20'
  main: 'dist/index.js'
