name: 'Organization Repository to Project'
description: 'Action to copy project automation workflow'
inputs:
  repo-token:
    description: 'A GitHub access token secret - must have the admin:org scope'
runs:
  using: 'node20'
  main: 'dist/index.js'
