name: 'Organization Project Automation Workflow'
description: 'Action to copy the project automation workflow across company\'s repositories'
inputs:
  secrets:
    description: 'GitHub secrets'
    required: true
  org:
    description: 'The GitHub organization slug'
    default: 'caseproof'
  process_deletion:
    description: 'When set to `true` the action will also delete the project automation workflow from repositories which are not associated to any teams/projects. Default is `false`'
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
