name: 'Organization Project Automation Workflow'
description: 'Action to copy project automation workflow'
inputs:
  repo-token:
    description: 'A GitHub access token secret - must have the workflows read/write permissios'
  org:
    description: 'The github organization slug'
runs:
  using: 'node20'
  main: 'dist/index.js'
