name: Sync Organization Files

on:
  push:
    paths:
      # Templates.
      - .github/workflow-templates/project-automation.yml

      # Defs.
      - .github/workflows/teams-config.yml

      # When this file is edited.
      - .github/workflows/workflow-sync.yml
    branches:
      - trunk
  workflow_dispatch:

env:
  ORGANIZATION: 'caseproof'


jobs:
  projects:
    name: Project Automation Workflow Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync project-automation
        uses: ./.github/actions/project-automation
        with:
          org: ${{ env.ORGANIZATION }}
          secrets: ${{ toJson(secrets) }}
