name: Sync Organization Files

on:
  push:
    paths:
      # Utils.
      - .github/workflows-templates/project-automation.yml

      # Defs.
      - team-config.yml

      # When this file is edited.
      - .github/workflows/workflow-sync.yml
    branches:
      - trunk
  workflow_dispatch:

env:
  ORGANIZATION: 'riflessidigitali'


jobs:
  projects:
    name: Project Automation Workflow Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync project-automation
        uses: ./.github/actions/project-automation
        with:
          token: ${{ secrets.CSPF_REPO_READ_PAT }}
          org: ${{ env.ORGANIZATION }}
